export default {
  'planner.disclaimer.title': "IMPORTANT NOTICE",
  'planner.disclaimer.description': 'This dive planner is designed to assist in creating dive profiles based on theoretical decompression calculations. These profiles are experimental and should not be utilized without an understanding of the inherent risk of Decompression Sickness (DCS). No dive planning tool can guarantee avoidance of DCS. The only sure way to mitigate risk of DCS is to avoid diving altogether. This site and its creators accept no responsibility for any injuries or complications arising from use of profiles generated by this tool. Always seek certified professional training and advice before diving.',
} as const
