service: divenerd-api

plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 9000

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-3

functions:
  graphql:
    handler: src/index.graphql
    events:
      - http:
          path: graphql
          method: ANY
          cors: true
