name: API - Build and deploy to AWS
on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Deploy to DEV
        run: yarn api deploy --stage dev
      - name: Deploy to PROD
        run: yarn api deploy --stage prod
