name: API - Build and deploy to AWS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
      - name: Deploy to DEV
        run: yarn api deploy --stage dev
      - name: Deploy to PROD
        run: yarn api deploy --stage dev
